version: "3"

services:
  database:
    image: "mariadb:latest"
    ports: 
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    links:
      - redis
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: /../../docker/php
    restart: 'always'
    volumes:
      - ./www:/var/www/html/
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./php/content:/srv/www/content
      - ./static:/srv/www/static
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - C:\Users\jsomh\Projects\ubbgenerator\MovieUbbGenerator\www\:/app
  redis:
    container_name: 'redis'
    ports:
      - '6379:6379'
    image: redis:latest
    volumes:
      - ./redis:/data
