version: "3"

services:
  database:
    image: "mariadb:latest"
    ports: 
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    links:
      - redis
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: /../../docker/php
    restart: 'always'
    ports:
      - '8080:80'
    volumes:
      - ./www:/var/www/html/
  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - C:\Users\jsomh\Projects\ubbgenerator\MovieUbbGenerator\www\:/app
  redis:
    container_name: 'redis'
    ports:
      - '6379:6379'
    image: redis:latest
    volumes:
      - ./redis:/data
