<?php

namespace App\Repository;

use App\Entity\ReviewEntity;
use App\model\Review;
use App\Model\Wrappers\ReviewApiWrapper;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param int $limit
     * @return ReviewEntity[]
     */
    public function findLatest(int $limit = 10) :array{
        $qb = $this->createQueryBuilder('r')
          ->orderBy('r.reviewid','DESC')
            ->setMaxResults($limit);
        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function store(Review $review) : Review
    {
        $reviewEntity = ReviewApiWrapper::unwrap($review);
        $this->getEntityManager()->persist($reviewEntity);
        $this->getEntityManager()->flush();
        return ReviewApiWrapper::wrap($reviewEntity);

    }


}
